// Generated on 2013-12-15 using generator-angular 0.6.0
'use strict';

// # Globbing
// for performance reasons we're only matching one level down:
// 'test/spec/{,*/}*.js'
// use this if you want to recursively match all subfolders:
// 'test/spec/**/*.js'

module.exports = function (grunt) {

  // just-in-time plugin loader
  require('jit-grunt')(grunt, {
    ngtemplates: 'grunt-angular-templates',
    useminPrepare: 'grunt-usemin'
  });

  // Time how long tasks take. Can help when optimizing build times
  require('time-grunt')(grunt);

  // https://github.com/kangax/html-minifier#options-quick-reference
  var htmlminOptions = {
    collapseBooleanAttributes: true,
    collapseWhitespace: true,
    conservativeCollapse: true, // collapse to 1 space
    removeAttributeQuotes: true,
    removeComments: true,
    removeEmptyAttributes: false,
    removeRedundantAttributes: true
  };

  // Define the configuration for all the tasks
  grunt.initConfig({

    // configurable paths
    paths: {
      app: require('./bower.json').appPath || 'app',
      dist: 'dist',
      distStatic: 'dist-static',
      url: 'http://localhost'
    },

    // Watches files for changes and runs tasks based on the changed files
    watch: {
      gruntfile: {
        files: ['Gruntfile.js']
      },
      livereload: {
        options: {
          livereload: '<%= connect.options.livereload %>'
        },
        files: [
          '<%= paths.app %>/*.html',            // exclude template source files
          '<%= paths.app %>/.tmp/templates.js', // generated by ngtemplates
          '<%= paths.app %>/.tmp/css/*.css'     // generated by compass:watch
        ]
      },
      ngtemplates: { // regenerate Angular templates
        tasks: ['ngtemplates'],
        files: ['app/partials/*.html']
      }
    },

    // The actual grunt server settings
    connect: {
      options: {
        port: 9000,
        // Change this to '0.0.0.0' to access the server from outside.
        hostname: 'localhost',
        livereload: 35729
      },
      livereload: {
        options: {
          open: true,
          base: ['<%= paths.app %>']
        }
      },
      test: {
        options: {
          port: 9001,
          base: [
            'test',
            '<%= paths.app %>'
          ]
        }
      },
      dist: {
        options: {
          base: '<%= paths.dist %>'
        }
      }
    },

    // Make sure code styles are up to par and there are no obvious mistakes
    jshint: {
      options: {
        jshintrc: '.jshintrc',
        reporter: require('jshint-stylish')
      },
      all: [
        'Gruntfile.js',
        '<%= paths.app %>/js/**/*.js'
      ],
      test: {
        options: {
          jshintrc: 'test/.jshintrc'
        },
        src: ['test/spec/{,*/}*.js']
      }
    },

    // Empties folders to start fresh
    clean: {
      dist: {
        files: [{
          dot: true,
          src: [
            '.tmp',
            '<%= paths.dist %>/*',
            '!<%= paths.dist %>/.git*'
          ]
        }]
      },
      distStatic: ['<%= paths.distStatic %>'],
      server: '.tmp'
    },

    // Add vendor prefixed styles
    autoprefixer: {
      options: {
        browsers: ['last 1 version']
      },
      dist: {
        files: [{
          expand: true,
          cwd: '.tmp/css/',
          src: '{,*/}*.css',
          dest: '.tmp/css/'
        }]
      }
    },

    // Renames files for browser caching purposes
    rev: {
      dist: {
        files: {
          src: [
            '<%= paths.dist %>/js/{,*/}*.js',
            '<%= paths.dist %>/css/{,*/}*.css',
            '<%= paths.dist %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
            '<%= paths.dist %>/css/fonts/*'
          ]
        }
      }
    },

    // Reads HTML for usemin blocks to enable smart builds that automatically
    // concat, minify and revision files. Creates configurations in memory so
    // additional tasks can operate on them
    useminPrepare: {
      html: '<%= paths.app %>/index.html',
      options: {
        dest: '<%= paths.dist %>'
      }
    },

    // Performs rewrites based on rev and the useminPrepare configuration
    usemin: {
      html: ['<%= paths.dist %>/{,*/}*.html'],
      css: ['<%= paths.dist %>/css/{,*/}*.css'],
      options: {
        assetsDirs: ['<%= paths.dist %>']
      }
    },

    // The following *-min tasks produce minified files in the dist folder
    // imagemin: {
    //   dist: {
    //     files: [{
    //       expand: true,
    //       cwd: '<%= paths.app %>/images',
    //       src: '{,*/}*.{png,jpg,jpeg,gif}',
    //       dest: '<%= paths.dist %>/images'
    //     }]
    //   }
    // },
    // svgmin: {
    //   dist: {
    //     files: [{
    //       expand: true,
    //       cwd: '<%= paths.app %>/images',
    //       src: '{,*/}*.svg',
    //       dest: '<%= paths.dist %>/images'
    //     }]
    //   }
    // },
    htmlmin: {
      dist: {
        options: htmlminOptions,
        files: [{
          expand: true,
          cwd: '<%= paths.dist %>',
          src: '*.html',
          dest: '<%= paths.dist %>'
        }]
      }
    },

    ngAnnotate: {
      dist: {
        files: [{
          expand: true,
          cwd: '.tmp/concat/js',
          src: '*.js',
          dest: '.tmp/concat/js'
        }]
      }
    },

    // Copies remaining files to places other tasks can use
    copy: {
      dist: {
        files: [{
          expand: true,
          dot: true,
          cwd: '<%= paths.app %>',
          dest: '<%= paths.dist %>',
          src: [
            '**',
            '!.tmp/**',
            '!bower_components/**',
            '!css/**',
            '!js/**',
            '!partials/**'
          ]
        }, {
          // optional remote version of config.php
          expand: true,
          cwd: '<%= paths.app %>',
          dest: '<%= paths.dist %>',
          src: [
            'config-remote.php'
          ],
          rename: function (dest) {
            return dest + '/config.php';
          }
        }, {
          expand: true,
          cwd: '.tmp/images',
          dest: '<%= paths.dist %>/images',
          src: [
            'generated/*'
          ]
        }]
      },
      distStatic: {
        expand: true,
        cwd: '<%= paths.dist %>',
        dest: '<%= paths.distStatic %>',
        src: [
          'css/**/*',
          'js/**/*',
          'index.html'
        ]
      },
      styles: {
        expand: true,
        cwd: '<%= paths.app %>/.tmp/css',
        dest: '.tmp/css',
        src: '{,*/}*.css'
      }
    },

    // Run some tasks in parallel to speed up the build process
    concurrent: {
      server: [
        'copy:styles'
      ],
      test: [
        'copy:styles'
      ],
      // dist: [
      //   'copy:styles',
      //   'imagemin',
      //   'svgmin',
      //   'htmlmin'
      // ],
      watch: {
        tasks: [
          'watch',
          'compass:watch'
        ],
        options: {
          logConcurrentOutput: true
        }
      }
    },

    // By default, your `index.html`'s <!-- Usemin block --> will take care of
    // minification. These next options are pre-configured if you do not wish
    // to use the Usemin blocks.
    // cssmin: {
    //   dist: {
    //     files: {
    //       '<%= paths.dist %>/css/main.css': [
    //         '.tmp/css/{,*/}*.css',
    //         '<%= paths.app %>/css/{,*/}*.css'
    //       ]
    //     }
    //   }
    // },
    // uglify: {
    //   dist: {
    //     files: {
    //       '<%= paths.dist %>/js/scripts.js': [
    //         '<%= paths.dist %>/js/scripts.js'
    //       ]
    //     }
    //   }
    // },
    // concat: {
    //   dist: {}
    // },

    // Test settings
    karma: {
      unit: {
        configFile: 'karma.conf.js',
        singleRun: true
      }
    },

    compass: {
      watch: { // dev
        options: {
          sassDir: '<%= paths.app %>/css/sass',
          cssDir: '<%= paths.app %>/.tmp/css',
          watch: true, // use the native compass watch command
          bundleExec: true
        }
      },
      dist: { // compile once
        options: {
          sassDir: '<%= paths.app %>/css/sass',
          cssDir: '.tmp/css',
          bundleExec: true
        }
      }
    },

    ngtemplates: {
      app: { // module name
        cwd: 'app/partials',
        src: '*.html',
        dest: '<%= paths.app %>/.tmp/templates.js',
        options: {
          htmlmin: htmlminOptions
        }
      }
    },

    htmlrefs: {
      dist: {
        src: '<%= paths.dist %>/index.html',
        dest: '<%= paths.dist %>/index.html'
      }
    },
  });


  grunt.registerTask('dev', ['concurrent:watch']);

  grunt.registerTask('serve', function (target) {
    if (target === 'dist') {
      return grunt.task.run(['build', 'connect:dist:keepalive']);
    }

    grunt.task.run([
      'clean:server',
      'concurrent:server',
      'autoprefixer',
      'connect:livereload',
      'watch'
    ]);
  });

  grunt.registerTask('server', function () {
    grunt.log.warn('The `server` task has been deprecated. Use `grunt serve` to start a server.');
    grunt.task.run(['serve']);
  });

  grunt.registerTask('test', [
    'clean:server',
    'concurrent:test',
    'autoprefixer',
    'connect:test',
    'karma'
  ]);

  grunt.registerTask('build', [
    'clean:dist',
    'ngtemplates',
    'compass:dist',
    'useminPrepare',
    'copy:styles', // 'concurrent:dist',
    'autoprefixer',
    'concat',
    'ngAnnotate',
    'copy:dist',
    'cssmin',
    'uglify',
    'rev',
    'usemin',
    'htmlrefs',
    'htmlmin',
  ]);

  // generate .json files in dist-static/api by copying output from the PHP API
  grunt.registerTask('generateStaticAPI', function () {
    var request = require('request');
    var async = require('async');
    var _ = require('lodash');

    var src = grunt.config('paths.url') + '/' + grunt.config('paths.app') +
      '/api';
    var dest = grunt.config('paths.distStatic') + '/api';

    var done = this.async();

    // copy the file at the given path, then call the optional callback
    var copy = function (path, callback) {
      request(src + '/' + path, function (error, response, body) {
        // log
        grunt.log.write('writing:', path, '... ');

        // catch errors
        if (error) {
          grunt.log.error(error);
          return;
        }
        if (response.statusCode !== 200) {
          grunt.log.error('status code:', response.statusCode);
          return;
        }

        // save the body
        grunt.file.write(dest + '/' + path, body);

        // log
        grunt.log.ok('written:', path);

        // callback
        if (typeof callback === 'function') {
          callback(error, response, body);
        }
      });
    };

    // helper method to flatten the dirs tree; see RefilerModel
    var flatten = function (dirs) {
      var result = [];
      _.each(dirs, function (dir) {
        result.push(dir);
        result = result.concat(flatten(dir.subdirs));
      });
      return result;
    };

    // copy init.json, then parse its data to copy the other files
    copy('init.json', function (error, response, body) {
      // parse data
      var data = JSON.parse(body);

      // store all paths for use in the loop below
      var paths = [];
      data.tags.forEach(function (tag) {
        paths.push('tag/' + tag.id + '.json');
      });
      flatten(data.dirs).forEach(function (dir) {
        paths.push('dir/' + dir.id + '.json');
      });

      // use async.each to take advantage of its callback when all iterator
      // functions have finished, where we can call done()
      async.each(paths, function (path, callback) {
        // copy the file
        copy(path, function () {
          callback();
        });
      }, function (error) {
        if (error) {
          grunt.log.error('error in async loop:', error);
          return;
        }
        done();
      });
    });
  });

  grunt.registerTask('buildStatic', [
    'clean:distStatic',
    'copy:distStatic',
    'generateStaticAPI',
  ]);

  grunt.registerTask('default', [
    'newer:jshint',
    'test',
    'build'
  ]);
};
